FROM python
RUN pip install flask
RUN pip install flask_sqlalchemy
RUN pip install flask_login
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  web.py /home/myapp/
COPY  UserList.sqlite /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/web.py
